In [1]:
import numpy as np


In [2]:
my_first_array = np.array([1,2,3,4,5])
print(my_first_array)
print(type(my_first_array))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
distance_in_kms = [2.1, 4.9, 5.6, 7.8] 

In [4]:
distance_in_ms = [item*1000 for item in distance_in_kms]
print(distance_in_ms)

[2100.0, 4900.0, 5600.0, 7800.0]


In [5]:
print(np.array(distance_in_kms)*1000)

[2100. 4900. 5600. 7800.]


In [6]:
print(len(np.array(distance_in_kms)))

4


In [11]:
a=np.array([1,'a',3])
print(a)
print(type(a))

['1' 'a' '3']
<class 'numpy.ndarray'>


In [12]:
a = np.arange(1, 10, 4)
print(a)
print(type(a))

[1 5 9]
<class 'numpy.ndarray'>


In [13]:
a_2 = range(1,10,4)
print(list(a_2))

[1, 5, 9]


In [14]:
#default step of 1 and start from 0
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [15]:
x = np.arange(0.5, 13.2, 0.7)
print(x)

[ 0.5  1.2  1.9  2.6  3.3  4.   4.7  5.4  6.1  6.8  7.5  8.2  8.9  9.6
 10.3 11.  11.7 12.4 13.1]


In [17]:
int_array = np.array([1.,2,3,4,5])
print(int_array.dtype)
print(int_array.ndim)
print(type(int_array))

float64
1
<class 'numpy.ndarray'>


In [18]:
print(int_array[:-1])

[1. 2. 3. 4.]


In [19]:
print(int_array[::-1])

[5. 4. 3. 2. 1.]


In [90]:
array_of_floats = np.array([5.5, 5.4, 4.11, 6.0, 6.2, 5.8, 7.1], float)
print(type(array_of_floats.dtype))
array_of_floats

<class 'numpy.dtype'>


array([5.5 , 5.4 , 4.11, 6.  , 6.2 , 5.8 , 7.1 ])

In [42]:
print(array_of_floats.mean())

5.7299999999999995


In [43]:
print(np.median(array_of_floats))

5.8


In [44]:
print(array_of_floats.max())

7.1


In [45]:
#Index of Max value
print(array_of_floats.argmax())

6


In [ ]:
print(array_of_floats>5.5) 

In [48]:
greater_than = a>5.5
print(any(greater_than))
print(all(greater_than))
print(greater_than)

True
False
[False False  True]


In [49]:
first_array = np.array([1,2,3])
second_array = np.array([4,5,6])
print(np.concatenate((first_array,second_array)))

[1 2 3 4 5 6]


In [62]:
first_matrix = np.arange(30).reshape(5,6)
second_matrix=np.array([1,2,3,4]).reshape(2,2)

In [78]:
print(first_matrix.shape)
print(first_matrix)
print(type(first_matrix))
print(first_matrix.dtype)
print(second_matrix)

(5, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
<class 'numpy.ndarray'>
int32
[[1 2]
 [3 4]]


In [79]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [87]:
#initiate array of ones and zeros
a = np.ones((4,4),dtype=int)
print(a)
print(type(a.dtype))
a.resize(3,6)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
<class 'numpy.dtype'>
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 0 0]]


In [80]:
#find the max
print(first_matrix)
print("The max is : {0} ".format(first_matrix.max()))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
The max is : 29 


In [81]:
#max of each row
print("The max is : {0}".format(first_matrix.max(axis=1)))

The max is : [ 5 11 17 23 29]


In [69]:
#sum of each row
print("The sum is : {0}".format(first_matrix.sum(axis=1)))


The sum is : [ 15  51  87 123 159]


In [70]:
#np arrays vs lists

#adding lists
first_list = [1,2,3]
second_list = [4,5,6]

print(first_list+second_list) #concatenates
print(np.array(first_list) + np.array(second_list)) #element-wise adddition

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
print(np.array(first_list)/np.array(second_list)) 


In [96]:
x=np.arange(30)
y=x.reshape(3,10)
print(y)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [103]:
print(y[1,2:4])
print(y[0,:3])

[12 13]
[0 1 2]


In [109]:
print(y[0,[1,6]])
[y[0,i] for i in [0,2]]

[1 6]


[0, 2]

In [105]:
print(y[y>4])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29]


In [106]:
#Uniform Distribution
np.random.rand(10)

array([0.74610597, 0.25408167, 0.18259014, 0.89622774, 0.20612362,
       0.03134777, 0.6097076 , 0.41906034, 0.52415663, 0.55335827])

In [107]:
#Normal distribution
np.random.randn(10)

array([ 0.74065294,  1.2443043 ,  0.61318109,  0.66594442, -0.4321503 ,
        2.41058139,  0.80103485,  0.01846189,  1.41328131,  0.8935851 ])

In [127]:
import time
size_of_vec = 100000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

In [128]:
t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.24116039276123047 0.0010004043579101562
Numpy is in this example 241.06291706387034 faster!
